# Generated by Django 5.1.6 on 2025-04-02 15:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_task_status_historicaltask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='comletion_evidence_link',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='obligation',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obligation',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pva',
            name='link',
            field=models.CharField(default=django.utils.timezone.now, max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pva',
            name='medicinal_products',
            field=models.ManyToManyField(to='api.medicinalproduct'),
        ),
        migrations.AddField(
            model_name='task',
            name='comletion_evidence_link',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.task'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Не начата'), ('In Progress', 'В работе'), ('Completed', 'Завершена')], default='Not Started', max_length=50),
        ),
        migrations.AlterField(
            model_name='pva',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Не начата'), ('In Progress', 'В работе'), ('Completed', 'Завершена')], default='Not Started', max_length=50),
        ),
        migrations.AlterField(
            model_name='taskschedule',
            name='frequency_type',
            field=models.IntegerField(choices=[('D', 'Ежедневно'), ('W', 'Каждую неделю'), ('M', 'Каждый месяц'), ('Y', 'Каждый год')], default='D'),
        ),
        migrations.DeleteModel(
            name='ObligationMedicinalProduct',
        ),
    ]
