# Generated by Django 5.1.6 on 2025-04-02 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_timestamp_comment_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='comletion_evidence_link',
            new_name='completion_evidence_link',
        ),
    ]
