# Generated by Django 5.1.6 on 2025-04-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_comletion_evidence_link_historicaltask_completion_evidence_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinalproduct',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='obligation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pva',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='completion_evidence_link',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='HistoricalTask',
        ),
    ]
