# Generated by Django 5.1.6 on 2025-05-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_medicinalproduct_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinalproduct',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='pva',
            name='requisites',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='responsibilitytype',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NS', 'Не начата'), ('IP', 'В работе'), ('C', 'Завершена'), ('H', 'Скрыта')], default='NS', max_length=50),
        ),
    ]
