# Generated by Django 5.1.6 on 2025-05-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_medicinalproduct_title_alter_partner_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pva',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='pva',
            name='link',
        ),
        migrations.AddField(
            model_name='pva',
            name='main_contract_link',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='pva',
            name='pva_link',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='pva',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pva',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pva',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Планируемый'), ('ACTIVE', 'Заключен'), ('ENDING', 'Завершающийся'), ('COMPLETED', 'Завершен')], default='PLANNED', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Не начата'), ('IN_PROGRESS', 'В работе'), ('COMPLETED', 'Завершена'), ('HIDDEN', 'Скрыта')], default='NOT_STARTED', max_length=20),
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
    ]
