# Generated by Django 5.1.6 on 2025-05-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_pva_partner_remove_pva_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskschedule',
            name='frequency_type',
            field=models.CharField(choices=[('D', 'Ежедневно'), ('W', 'Каждую неделю'), ('M', 'Каждый месяц'), ('Y', 'Каждый год')], default='D', max_length=1),
        ),
    ]
