# Generated by Django 5.1.6 on 2025-05-05 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_task_api_task_status_2aef03_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='api.taskschedule'),
        ),
    ]
