# Generated by Django 5.1.6 on 2025-05-06 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_task_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача'},
        ),
    ]
