# Generated by Django 5.1.6 on 2025-05-06 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='medicinalproduct',
            options={'verbose_name': 'Лекарственный препарат', 'verbose_name_plural': 'Лекарственные препараты'},
        ),
        migrations.AlterModelOptions(
            name='obligation',
            options={'verbose_name': 'Обязательство', 'verbose_name_plural': 'Обязательства'},
        ),
        migrations.AlterModelOptions(
            name='pva',
            options={'verbose_name': 'Договор', 'verbose_name_plural': 'Договоры'},
        ),
        migrations.AlterModelOptions(
            name='responsibilitytype',
            options={'verbose_name': 'Тип обязательства', 'verbose_name_plural': 'Типы обязательств'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterModelOptions(
            name='taskschedule',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписания'},
        ),
    ]
